# Imports ----------------------------------------------------------------------

#' @import dplyr
#' @import tidyr
#' @import ggplot2
#' @import phyloseq
#' @import rlang
#' @import pipeR
#' @import tibble

NULL

# Objects ----------------------------------------------------------------------

cols_21 = rev(c("#4f8579","#783fcc","#69d24d","#cb4bbd","#c6dc46","#542871",
            "#78d792","#cc4472","#83d7d0","#d44d33","#676fcd","#ceb854",
            "#403d57","#b97839","#84a4cb","#588038","#c68ac4","#48472a",
            "#c9c39c","#6e2b34","#c78889"))
cols_31 = rev(c("#69006f","#62e622","#cf00d0","#00a60c","#8568ff","#01e479",
            "#ff4562","#00dda5","#bc0024","#7cffff","#630039","#daff8b",
            "#00285d","#dbb600","#ff7fc4","#8dae00","#a7d0ff","#9e5000",
            "#bcf2ff","#662000","#f1ffd0","#241500","#ffdfe7","#376b00",
            "#ff8d6d","#00322c","#ff9d44","#005e75","#ffce96","#3c4400",
            "#695000"))
acols_60 = c("#f44400","#6151fe","#66f035","#3015be","#c2ff29","#7d00be",
			"#fbf700","#01189d","#86ff6c","#8d00a6","#3db500","#ff3fd6",
			"#01c145","#b277ff","#809900","#0058ca","#f5ff80","#23005d",
			"#00b765","#f70078","#00be90","#de0081","#00d6d5","#ff343d",
			"#00bbfd","#ba0004","#01badf","#ff496c","#00562a","#ff7fde",
			"#456800","#a391ff","#a67c00","#002368","#ffa74c","#016cb1",
			"#aa4f00","#0091c7","#ffe18e","#970077","#d1ffcb","#5e0044",
			"#bae4e5","#350001","#e6b3ff","#2c4900","#ff96ae","#001d18",
			"#ffccd7","#280020","#ffb3a4","#003559","#786200","#008292",
			"#790036","#00775f","#540d00","#373738","#5b3300","#352f00")
cols_60 = rev(c("#005981","#71e000","#5b4cf8","#d0e400","#6600b2","#01c54e",
               "#da1ada","#dbff76","#003daa","#a6a700","#948dff","#e29700",
               "#003787","#96ff9c","#b4007c","#01cb7d","#f2006a","#01eeb9",
               "#ee3e00","#1dfff2","#b70028","#01b284","#ff52b5","#007b20",
               "#ff86e2","#002e02","#e1a4ff","#525900","#920072","#b0ffc9",
               "#39004c","#ffe689","#001a52","#ffb869","#006abc","#a96800",
               "#64b6ff","#9d2f00","#81efff","#ff545c","#01a8aa","#8b003e",
               "#e7ffd0","#440032","#fefffe","#030017","#ff925b","#0092bd",
               "#ff8463","#028899","#600017","#c8e3ff","#702f00","#f0d4ff",
               "#1f1100","#ffc18a","#003138","#ffbcbd","#01704c","#432b00"))
cols_70 = rev(c("#00cf9b","#fc00bf","#52e62c","#a000b2","#9fff37","#5066ff",
			   "#c2de00","#003ebb","#69c500","#cf69ff","#8dff6e","#1f0063",
			   "#ffed43","#9572ff","#01a30f","#ff64df","#01ce53","#76007c",
			   "#7cff8e","#0057cc","#ffc93a","#4191ff","#de0200","#1af4ff",
			   "#cc003a","#01d57d","#ca0057","#00e5d4","#a3001c","#8dffc7",
			   "#ac0053","#a5ffa9","#003a8a","#d0ff8d","#001f50","#94a600",
			   "#cbaeff","#4e9100","#ffb1f8","#3f8100","#ff9acd","#006b32",
			   "#ff6c62","#00aec9","#dc5f00","#004a72","#c08c00","#260021",
			   "#ffe08c","#001524","#deffd6","#2c0100","#c8f8ff","#660014",
			   "#9fd4ff","#701a00","#dcd0ff","#003c11","#ffd9f4","#181500",
			   "#ffd8a1","#00332c","#ff8763","#018b69","#9d5d00","#006a7f",
			   "#ffae8e","#472700","#ffb4b6","#807100"))

# Functions --------------------------------------------------------------------

## Functions to generate taxa bar charts ---------------------------------------

### Deal with data -------------------------------------------------------------


##### df_glom ------------------------------------------------------------------

#' Like tax_glom, but for data frames
#'
#' \code{df_glom} take totals within sample at a given taxonomic rank.
#'
#' @param phy_df A phyloseq data frame, as generated by \code{\link{psmelt}} or
#'   \code{\link{make_phy_df}}
#' @param ranks A character vector with the taxon rank names
#' @param IDcol The column name of the sample IDs
#' @param rank The taxonomic rank to glom at
#' @param abunds The column name of the abundances to sum
#' @param tots The desired column name of the summed (glommed) abundances
df_glom = function(phy_df, ranks, IDcol = 'X.SampleID', rank = 'Phylum',
                   abunds = 'Abundance'){

    # Set up the groups for the plotting totals
    phy_df %>%
        group_by_at(vars(IDcol,rank)) %>%
        mutate(TotalAbunds = sum(UQ(sym(abunds)))) %>%
        data.frame() -> glommed_df

    return(glommed_df)
}

##### subset_order -------------------------------------------------------------

#' Subset and generate taxon ordering
#'
#' \code{subset_order} generates a data frame whose taxon column given by
#' \code{rank} has been ranked according to its mean abundance in the
#' \code{abunds} column.
#'
#' @param phy_df A phyloseq data frame, as generated by \code{\link{psmelt}}, but
#'   probably generated by \code{\link{df_glom}}.
#' @param varbs (\code{NULL}) A character vector of grouping variables from
#'   which the baseline values are chosen to define the abundance ordering. If
#'   it is \code{NULL}, the ordering will be based on mean abundances in the
#'   whole data frame.
#' @param bases (\code{NULL}) A character vector of baseline values for the
#'   variables given in \code{vars}. The ordering of the taxa will be given
#'   based only on the samples with these baseline values for these variables.
#'   Must be in the same order as varbs.
#' @param abund (\code{'Abundance'}) The name of the abundance column.
#' @param rank (\code{'Genus'}) The rank to base the ordering on.
subset_order = function(phy_df, varbs = NULL, bases = NULL, rank = 'Genus',
                        abunds = 'TotalAbunds'){
    # Check inputs
    if (is.null(varbs)){
        warn('No grouping variables given. Using whole data set.')
    } else if (is.null(bases)){
        warn(paste('No baseline values given for grouping variables.',
                    'Using whole data set.'))
    } else if (length(varbs) != length(bases)){
        stop('vars and bases must have the same length.')
    }


    # Subset and order
    ranked = phy_df
    for(i in 1:length(varbs)){
        ranked %>% filter(UQ(sym(varbs[i])) == bases[i]) -> ranked
    }
    ranked %>%
        group_by_at(vars(c(varbs,rank))) %>%
        summarize(MetaMean = mean(UQ(sym(abunds)))) %>%
        data.frame() %>%
        order_taxa(rank, 'MetaMean', decreasing = TRUE) -> ranked

    return(ranked)
}

##### rank_abund ---------------------------------------------------------------

#' Rank Taxa by Abundance
#'
#' \code{rank_abund()} generates a data frame that's ready to be used by
#' \code{\link{plot_rank_abund}}
#'
#' @section Value: A data frame whose taxa have been ranked by their mean
#'   abundance in the baseline level of some grouping variable or variables.
#'
#' @param phy_df A dataframe of a phyloseq object, like that generated by
#'   \code{\link{psmelt}} or \code{\link{make_phy_df}}
#' @param varbs (\code{NULL}) A character vector of grouping variables from
#'   which the baseline values are chosen to define the abundance ordering. If
#'   it is \code{NULL}, the ordering will be based on mean abundances in the
#'   whole data frame.
#' @param bases (\code{NULL}) A character vector of baseline values for the
#'   variables given in \code{vars}. The ordering of the taxa will be given
#'   based only on the samples with these baseline values for these variables.
#'   Must be in the same order as vars.
#' @param abunds (\code{'Abundance'}) The name of the abundance column.
#' @param rank (\code{'Genus'}) The rank to base the ordering on.
#' @param IDcol (\code{'X.SampleID'}) The column name of the sample IDs
rank_abund = function(phy_df, varbs = NULL, bases = NULL, abunds = 'Abundance',
                      rank = 'Genus', IDcol = 'X.SampleID'){
    # Set up the groups for the plotting totals
    rank_abs = df_glom(phy_df, IDcol = IDcol, rank = rank, abunds = abunds)

    # Subset and order
    ranked = subset_order(rank_abs, varbs, bases, rank = rank)

    # Order the bigger data frame by the above ordering
    lev_ord = levels(ranked[,rank])
    rank_abs[,rank] = factor(rank_abs[,rank], levels = lev_ord)

    return(rank_abs)
}


#### order_levs

#' Order the levels of one factor by the values of another
#'
#' \code{order_levs()} takes two factors, the first of which has values that are
#' nested within the values of the second, and orders the levels of the first
#' factor such that they are clustered within the second factor.
#'
#' @section Value: A factor that has the same levels as f1, but that has been
#'   re-ordered.
#'
#' @param f1 The factor to re-order. Levels of this factor must be nested within
#'   \code{f2}
#' @param f2 The factor to use when re-ordering \code{f1}.
order_levs = function(f1,...){

    # if (is.numeric(f2)){
    #     ord = order(...)
    # } else {
        ord = order(...) # don't revert this to as-character. It needs to respect
                        # f2's level ordering. Find another way.
    # }

    lev_ord = unique(as.character(f1)[ord])
    f1 = factor(f1, levels = lev_ord)

    return(f1)
}

### Generate Plots -------------------------------------------------------------

#### rotate_ticks --------------------------------------------------------------

#' Rotate the x tick labels 90 degrees and position them correctly.
#'
rotate_ticks = function(){
    theme(axis.text.x = element_text(size = 10,
                                     angle = 90,
                                     hjust = 1,
                                     vjust = 0.5))
}

#### plot_tax_bar --------------------------------------------------------------

#' Create a Taxa Bar Chart
#'
#' \code{plot_tax_bar()} creates a taxa bar chart from the data frame generated
#' by \code{\link{make_phy_df}}.
#'
#' @section Details: This function generates a ggplot object that is a
#'   first-pass, reasonable attempt at a taxon bar chart. The taxa are ordered
#'   by mean abundance and the 'Other' category is at the top. Because it's a
#'   regular ggplot object, you can add more geoms or facet it or manipulate it
#'   however you like using ggplot functions.
#'
#' @section Value: A ggplot object.
#'
#' @param tax_df The data frame used for plotting. Unless you really know what
#'   you're doing, use the data frame output by \code{\link{make_phy_df}}.
#' @param rank The taxonomic rank at which to view the data. Must be one of
#'   'Genus', 'Family', 'Order', 'Class', 'Phylum'. May not be a lower rank than
#'   the rank given to \code{\link{make_phy_df}}.
#' @param colours A character vector of colour names or hex values. Must have
#'   enough colours to accommodate all your taxa at the appropriate rank. If you
#'   don't provide one, there are a few internal vectors that have 21, 31, 60,
#'   or 70 colours that the function will try to use.
#' @param sample The name of the sample column in the data frame.
#' @param abund The name of the abundance column in the data frame.
#' @param legloc Location of the legend. Can be 'right' (default), 'bottom', or
#'   'none' (absent)
#' @param yscale Can be either 'lin' or 'sqrt'. The 'sqrt' plot can look weird.
#' @param means If \code{TRUE}, sets \code{position = fill} in the
#'   \code{geom_bar()} to constrain the abundances to sum to 1. Good to use if
#'   your \code{sample = } parameter is not actually sample names, but rather
#'   larger categories, to produce means.
#' @export
plot_tax_bar = function(taxa_df,rank,colours = NULL,
					 sample = 'X.SampleID', abund = 'Abundance',
					 legloc = 'right', yscale = 'lin', means = FALSE){
	## taxa_df:	The data frame produced by taxa_other_df()
	## rank: The taxonomic rank to plot by
	## colours:	A character vector with the right number of colours. If you
	## don't provide one it uses my 21-colour vector, which might not be enough
	## left NULL, the bars will be ordered alphabetically by sample ID.
	## sample: the name of the sample ID column.
	## abund: the name of the abundance column

	# Check the inputs
	if (!(sample %in% names(taxa_df))){
		stop('sample argument must be one of the columns in your data frame')
	}

	if (!(abund %in% names(taxa_df))){
		stop('abund argument must be one of the columns in your data frame')
	}

	if (!(yscale %in% c('lin','log','sqrt'))){
		stop('yscale argument must be one of \'lin\', \'log\', or \'sqrt\'')
	}

	# Pick colours
	if (is.null(colours)){
		num = length(unique(taxa_df[,rank]))
		if (num <= 22){
			colours = c('grey69',rev(cols_21[1:(num-1)]))
		} else if (num <= 31) {
			colours = c('grey69',rev(cols_31[1:(num-1)]))
		} else if (num <= 61) {
			colours = c('grey69',rev(cols_60[1:(num-1)]))
		} else if (num <= 71) {
			colours = c('grey69',rev(cols_70[1:(num-1)]))
		} else {
			stop('I can\'t handle more than 71 ranks. Please provide a colour vector.')
		}
		# colours = case_when(
							#num <= 22 ~ c('grey69',cols_21),
							#num <= 32 ~ c('grey69',cols_31),
							#num <= 61 ~ c('grey69',cols_60),
							#num > 61 ~ c('grey69',cols_70))
	} else if (is.null(names(colours))) {
	    num = length(unique(taxa_df[,rank]))
		colours = c('grey69',rev(colours[1:(num-1)]))
	}

	# Make sure the x axis is categorical
	taxa_df[,sample] = factor(taxa_df[,sample])

	# If the colour vector is named, make sure it is ordered like the factor
	# it's colouring
	if (!is.null(names(colours))) {
	    taxa_df[,rank] = droplevels(taxa_df[,rank])
	    if (!all(levels(taxa_df[,rank]) %in% names(colours))){
	        stop('The colour vector names need to match the rank levels')
	    }

	    colours = colours[levels(taxa_df[,rank])]
	}

	indiv = ggplot(taxa_df, aes_string(x = sample, y = abund, fill = rank,
									   colour = rank)) +
	    theme(axis.title.x = element_blank(),
			axis.text.x = element_text(size = 10,
									   angle = 90,
									   hjust = 1,
									   vjust = 0.5)) +
	    scale_fill_manual(values = colours,
	                      guide = guide_legend(reverse = TRUE)) +
	    scale_colour_manual(values = colours,
	                        guide = guide_legend(reverse = TRUE)) +
	    ylab(paste("Relative Abundance (",rank,")\n",sep=''))
	if (means){
	    indiv = indiv + geom_bar(stat = 'identity', position = 'fill')
	} else {
	    indiv = indiv + geom_bar(stat = "identity")
	}

	if (yscale == 'sqrt') {
		indiv = indiv + scale_y_sqrt()
	}

	if (legloc == 'bottom'){
	    indiv = indiv + theme(legend.position = 'bottom')
	} else if (legloc == 'none') {
	    indiv = indiv + guides(fill = FALSE, colour = FALSE)
	}
	indiv + theme_bw()

	return(indiv)
}


## Functions to generate distance bar charts -----------------------------------

### lddf_check -----------------------------------------------------------------

#' Check the inputs of \code{long_distance_df()}
#'
#' For internal use only
lddf_check = function(dmat, metadat, idcol = 'X.SampleID', diag = FALSE,
                            suff = c('1','2')){

    # Check inputs
    if (!is.logical(diag)){
        stop('diag must be either TRUE or FALSE')
    }

    if ((length(suff) != 2) | (suff[1] == suff[2]) | (!is.character(suff))){
        stop('suff must be a vector of two non-identical strings')
    }

    if (!(idcol %in% colnames(metadat))){
        stop('idcol must be one of the column names of metadat')
    }

    # Check sample names

    ## If it's a proper distance matrix, it will have a "Labels" attribute
    if (!is.null(attr(dmat,'Labels'))){
        d_samps = attr(dmat, 'Labels')
    } else if (!is.null(colnames(dmat))){
        if (any(colnames(dmat) != rownames(dmat))){
            stop(paste('The row and column names of dmat must be the same,',
                        'and in the same order.'))
        } else {
            d_samps = colnames(dmat)
        }
    }

    if (!all(d_samps %in% as.character(metadat[,idcol]))){
        stop('Some samples missing from metadata')
    } else if (!all(as.character(metadat[,idcol]) %in% d_samps)){
        warning(paste('Metadata samples that are not in the distance matrix',
                        'will be excluded.'))
    }
}


### lddf_work ------------------------------------------------------------------

#' Does the actual gathering and spreading without testing assumptions
#'
#' \code{lddf_work} Does the actual gathering, spreading, and joining associated
#' with making the lddf, but without checking if the distance matrix is sensible
#' or removing diagonals and repeats. This is for when you know what you're
#' doing and have trimmed your distance matrix down to only what you know you
#' need. Good for permutation tests.
#'
#' @param dmat A distance matrix or other diagonal matrix object with sample
#'   names as row and column names.
#' @param metadat A data frame or data frame-like object with the data set's
#'   metadata
#' @param idcol (\code{'X.SampleID'}.) A string. The column in \code{metadat}
#'   that holds the sample names. Sample names should match the row/column namse
#'   of the distance matrix. If there are samples in the metadata data frame
#'   that are missing from the distance matrix, they will be excluded with a
#'   warning. If there are samples in the distance matrix that are missing from
#'   the metadata, you will get an error.
#' @param suff (\code{c('1','2')}.) A character vector of length 2. The suffixes
#'   to be appended to the metadata column names in the output. The two elements
#'   must not be identical.
#' @param distcol (\code{'Distance'}.) A string. The desired column name for the
#'   distance column in your long data frame. Only here to avoid clashes with
#'   existing metadata column names.
lddf_work = function(dmat, metadat, idcol = 'X.SampleID', suff = c('1','2'),
                     distcol = 'Distance'){
    # Make it long
    dmat %>>%
        {data.frame(ID1 = rownames(.),.)} %>%
        gather(ID2, Distance, 2:(ncol(dmat)+1), na.rm = TRUE) -> distlong

    ids = paste(idcol,suff, sep = '')
    names(distlong)[1:2] = ids

    # Add the metadata columns for the first sample
    distlong %>%
        inner_join(metadat, by = setNames(c(idcol), ids[1])) -> distlong

    # Add the suffix to the column names
    cn = colnames(distlong)
    cn = ifelse(cn %in% colnames(metadat),
                paste(cn, suff[1], sep = ''),
                cn)
    colnames(distlong) = cn

    # Add the metadata columns to the second sample
    distlong %>%
        inner_join(metadat, by = setNames(c(idcol), ids[2])) -> distlong

    # Add the suffix to the column names
    cn = colnames(distlong)
    cn = ifelse(cn %in% colnames(metadat),
                paste(cn, suff[2], sep = ''),
                cn)
    colnames(distlong) = cn

    return(distlong)
}

### long_distance_df -----------------------------------------------------------

#' Create a long data frame of among-sample distances
#'
#'
#' \code{long_distance_df} creates a long data frame of all the pairwise
#' distances from a sample distance matrix (e.g. the output of
#' \code{\link{phyloseq::distance}}) with all the metadata listed for each sample.
#' Allows for easy within- and among-group boxplots, or whatever other
#' comparisons are of interest.
#'
#' @section Value: A data frame \eqn{N(N-1)} (or \eqn{N^2} if \code{diag = TRUE}
#'   is set) rows (where N is the number of samples) with sample IDs, metadata,
#'   and pairwise distances listed for each pair of samples. Sample ID and
#'   metadata columns have '1' or '2' appended to them so the user can tell
#'   which column belongs to which sample.
#' @param dmat A distance matrix or other diagonal matrix object with sample
#'   names as row and column names.
#' @param metadat A data frame or data frame-like object with the data set's
#'   metadata
#' @param idcol (\code{'X.SampleID'}.) A string. The column in \code{metadat}
#'   that holds the sample names. Sample names should match the row/column namse
#'   of the distance matrix. If there are samples in the metadata data frame
#'   that are missing from the distance matrix, they will be excluded with a
#'   warning. If there are samples in the distance matrix that are missing from
#'   the metadata, you will get an error.
#' @param diag (\code{FALSE}.) Logical. Whether the diagonal elements (zeros in
#'   a distance matrix) should be included in the long data frame. Defaults to
#'   \code{FALSE} because we almost never want them.
#' @param suff (\code{c('1','2')}.) A character vector of length 2. The suffixes
#'   to be appended to the metadata column names in the output. The two elements
#'   must not be identical.
#' @param distcol (\code{'Distance'}.) A string. The desired column name for the
#'   distance column in your long data frame. Only here to avoid clashes with
#'   existing metadata column names.
#' @param baseline (\code{'NULL'}). A dataframe whose column names must also be
#'   column names in the metadat data frame, and whose rows contain a subset of
#'   the possible values/combinations. If this parameter is used, all the
#'   samples whose metadata matches a row in this data frame will end up in
#'   Sample1 and the rest will end up in Sample2. This means you will _not_ get
#'   all the pairs, because the samples in Sample1 will not get compared to each
#'   other, and neither will the samples in Sample2. If this parameter is not
#'   used, the upper triangle of the distance matrix is used, without regard for
#'   metadata values.
#' @export
long_distance_df = function(dmat, metadat, idcol = 'X.SampleID', diag = FALSE,
                            suff = c('1','2'), distcol = 'Distance',
                            baseline = NULL){

    # The sample data object does not play nice with others
    metadat = data.frame(metadat)

    # Check the inputs
    lddf_check(dmat, metadat, idcol, diag, suff)

    # Turn this into a usable matrix
    dmat = as.matrix(dmat)
    if (is.null(baseline)){
        if (diag) {
            dmat[upper.tri(dmat)]= NA
        } else {
            dmat[!lower.tri(dmat)] = NA
        }
    } else {
        s1 = inner_join(metadat, baseline, by = colnames(baseline))[,idcol]
        s2 = anti_join(metadat, baseline, by = colnames(baseline))[,idcol]
        dmat = dmat[as.character(s1),as.character(s2)]
    }

    lddf = lddf_work(dmat, metadat, idcol = idcol, suff = suff,
                     distcol = distcol)

    return(lddf)
}



## Functions to generate PCoA plots --------------------------------------------

### Make the data frame --------------------------------------------------------
#### axis_num ------------------------------------------------------------------

#' Get the axis number
#' Take a character vector of the form 'Axis.N' where N is a number and return
#' a numeric vector of N in the same order
#' @param AxisX The character vector of axes. Must only contain values of the
#' form 'Axis.N'
axis_num = function(AxisX){
    AxisX %>%
        strsplit('\\.') %>%
        unlist() -> tmp
    axes = as.numeric(tmp[seq(2,length(tmp),2)])

    return(axes)
}

#### make_rda_df----------------------------------------------------------------

#' Make a data frame of the ordination if the ordination method is RDA. Not
#' exported.
#'
#' Take a phyloseq object and generate a data frame of the distance-based
#' ordination of the samples for plotting when the ordination method was
#' RDA. Used internally by \code{make_ord_df()}
#'
#' @param ord The ordination object generated by \code{phyloseq::ordinate()}.
#' @param physeq The phyloseq object we're making things from
#' @param axes A numeric vector of the axes to plot
#' @export
make_rda_df = function(ord, physeq, axes){
    # Calculate the axis weights

    eigs = ord$CA$eig
    weights = round(eigs/sum(eigs), 3) * 100

    # Make the data frame
    ord_df = plot_ordination(physeq, ord, axes = axes, justDF = TRUE)
    ord_long = (ord_df
                %>% gather(AxisX, ValueX, starts_with('PC'))
                %>% left_join(ord_df)
                %>% gather(AxisY, ValueY, starts_with('PC'))
                %>% mutate(AxisX = paste(AxisX, paste(weights[AxisX], '%',
                                                      sep = '')),
                           AxisY = paste(AxisY, paste(weights[AxisY], '%',
                                                      sep = ''))))

    return(ord_long)
}

#### make_pcoa_df---------------------------------------------------------------

#' Make a data frame of the ordination if the ordination method is PCoA. Not
#' exported
#'
#' Take a phyloseq objet and generate a data frame of the distance-based
#' ordination of the samples for plotting when the ordination method was PCoA.
#' Used internally by \code{make_ord_df()}
#'
#' @param ord The ordination object generated by \code{phyloseq::ordinate()}.
#' @param physeq The phyloseq object we're making things from.
#' @param axes A numeric vector of the axes to include.
make_pcoa_df = function(ord, physeq, axes){
    # Calculate the axis weights
    weights = round(ord$values$Relative_eig, 3) * 100

    # Make the data frame
    ord_df = plot_ordination(physeq, ord, axes = axes, justDF = TRUE)
    ord_long = (ord_df
                %>% gather(AxisX, ValueX, starts_with('Axis.'))
                %>% left_join(ord_df)
                %>% gather(AxisY, ValueY, starts_with('Axis.'))
                %>% mutate(AxisX = factor(paste(AxisX,
                                        paste(weights[axis_num(AxisX)], '%',
                                                 sep = ''))),
                           AxisY = factor(paste(AxisY,
                                        paste(weights[axis_num(AxisY)], '%',
                                                 sep = '')))))
    return(ord_long)
}

#### make_ord_df --------------------------------------------------------------

#' Make a data frame of the ordination
#'
#' Take a phyloseq object and generate a data frame of the distance-based
#' ordination of the samples for plotting. This function has been tested with
#' ordination methods 'PCoA' and 'RDA'. I can't make any promises if you use a
#' different ordination method.
#'
#' @param physeq A phyloseq object with an OTU table and sample data. The table
#'   should be rarefied (or relative abundance) so that the distance metrics
#'   will be meaningful.
#' @param dist_meth The distance method to be use. Must be one of the methods
#'   accepted by the \code{phyloseq::distance()} function. Default is 'bray'. If
#'   'jaccard' is used, adds the \code{binary = TRUE} argument.
#' @param ord_meth The ordination method. Must be one of the methods accepted by
#'   the \code{phyloseq::ordinate()} function. Default is 'PCoA'.
#' @param scree_only If \code{TRUE}, this function will print the scree plot of
#'   the requested ordination and then exit. Good for deciding how many axes you
#'   care about. Default is \code{FALSE}.
#' @param axes A vector of integers indicating which ordination axes to include
#'   in the data frame. Defaults to \code{1:4}.
make_ord_df = function(physeq, dist_meth = 'bray', ord_meth = 'PCoA',
                  scree_only = FALSE, axes = 1:4){
    # Get the distance object and do the ordination
    if (dist_meth == 'jaccard'){
        d = distance(physeq, method = dist_meth, binary = TRUE)
    } else {
        d = distance(physeq, method = dist_meth)
    }
    ord = ordinate(physeq, ord_meth, d)

    # Scree
    if (scree_only) {
        print(phyloseq::plot_scree(ord))
        return()
    }

    if (ord_meth == 'PCoA'){
        ord_long = make_pcoa_df(ord, physeq, axes)
    } else if (ord_meth == 'RDA'){
        ord_long = make_rda_df(ord, physeq, axes)
    } else {
        ord_long = tryCatch(make_pcoa_df(ord, physeq, axes))
        if (is.data.frame(ord_long)){
            warn('Data frame produced, but untested with this ordination method. Double check before plotting.')
        } else {
            ord_long = tryCatch(make_rda_df(ord, physeq, axes))
            if (is.data.frame(ord_long)) {
                warn('Data frame produced, but untested with this ordination method. Double check before plotting.')
            } else {
                stop('Data frame could not be produced. Try \'PCoA\' or \'RDA\' ordination methods.')
            }
        }

        return(ord_long)
    }

    return(ord_long)

}

### Plot the ordination --------------------------------------------------------
#### plt_ord ------------------------------------------------------------------
#' Plot the ordination
#'
#' Make a multi-axis PCoA plot from the data frame
#' @param ord_long The ordination data frame produced by \code{make_ord_df}
#' @param colour The name of the column to use to colour the points.
#' @param shape The name of the coloumn governing the shape of the points.
#' @param size The size of the points. Passed to the \code{geom_point()} size
#' argument and defaults to 1.
#' @param pt_alph The transparency of the points. Default is 0.7
plt_ord = function(ord_long, colour = NULL, shape = NULL, size = 1,
                   pt_alph = 0.7){
    ord_plt = ggplot(ord_long, aes(ValueX, ValueY))

    if (!is.null(colour) & !(is.null(shape))) {
        ord_plt = ord_plt +
            geom_point(aes_string(colour = colour, shape = shape),
                       size = size,
                       alpha = pt_alph)
    } else if (!is.null(colour)){
        ord_plt = ord_plt +
            geom_point(aes_string(colour = colour), alpha = pt_alph, size = size)
    } else if (!is.null(shape)){
        ord_plt = ord_plt +
            geom_point(aes_string(shape = shape), alpha = pt_alph, size = size)
    } else {
        ord_plt = ord_plt +
            geom_point(alpha = pt_alph, size = size)
    }

    ord_plt = ord_plt +
        facet_grid(AxisY ~ AxisX)

    return(ord_plt)
}


## Miscellaneous Functions -----------------------------------------------------

#### plot_read_depth -----------------------------------------------------------

#' Plot read depth
#'
#' Creates a read depth histogram.
#' @param physeq A phyloseq object
#' @export
plot_read_depth = function(physeq){
    sample_sum_df = data.frame(Total = sample_sums(physeq),
                               sample_data(physeq))
    depth_plot = ggplot(sample_sum_df, aes(x = Total)) +
        geom_histogram(colour = 'black', fill = 'grey57') +
        scale_x_log10() +
        xlab('Log10 read depth') +
        ylab('Number of samples') +
        ggtitle('Distribution of read depths') +
        theme_bw()
    return(depth_plot)
}

#### plot_rank_ab --------------------------------------------------------------

#' Create a rank-abundance plot from a phyloseq data frame
plot_rank_ab = function(){

}
#### plot_alpha ----------------------------------------------------------------

#' Plot alpha diversity
#'
#' Plot the alpha diversity of a phyloseq data set.
#'
plot_alpha = function(physeq) {
    # rarefy

}


