## Functions to generate PCoA plots --------------------------------------------

### Make the data frame --------------------------------------------------------
#### axis_num ------------------------------------------------------------------

#' Get the axis number
#' Take a character vector of the form 'Axis.N' where N is a number and return
#' a numeric vector of N in the same order
#' @param AxisX The character vector of axes. Must only contain values of the
#' form 'Axis.N'
axis_num = function(AxisX){
    AxisX %>%
        strsplit('\\.') %>%
        unlist() -> tmp
    axes = as.numeric(tmp[seq(2,length(tmp),2)])

    return(axes)
}

#### make_rda_df----------------------------------------------------------------

#' Make a data frame of the ordination if the ordination method is RDA. Not
#' exported.
#'
#' Take a phyloseq object and generate a data frame of the distance-based
#' ordination of the samples for plotting when the ordination method was
#' RDA. Used internally by \code{make_ord_df()}
#'
#' @param ord The ordination object generated by \code{phyloseq::ordinate()}.
#' @param physeq The phyloseq object we're making things from
#' @param axes A numeric vector of the axes to plot
#' @export
make_rda_df = function(ord, physeq, axes){
    # Calculate the axis weights

    eigs = ord$CA$eig
    weights = round(eigs/sum(eigs), 3) * 100

    # Make the data frame
    ord_df = plot_ordination(physeq, ord, axes = axes, justDF = TRUE)
    ord_long = (ord_df
                %>% gather(AxisX, ValueX, starts_with('PC'))
                %>% left_join(ord_df)
                %>% gather(AxisY, ValueY, starts_with('PC'))
                %>% mutate(AxisX = paste(AxisX, paste(weights[AxisX], '%',
                                                      sep = '')),
                           AxisY = paste(AxisY, paste(weights[AxisY], '%',
                                                      sep = ''))))

    return(ord_long)
}

#### make_pcoa_df---------------------------------------------------------------

#' Make a data frame of the ordination if the ordination method is PCoA. Not
#' exported
#'
#' Take a phyloseq objet and generate a data frame of the distance-based
#' ordination of the samples for plotting when the ordination method was PCoA.
#' Used internally by \code{make_ord_df()}
#'
#' @param ord The ordination object generated by \code{phyloseq::ordinate()}.
#' @param physeq The phyloseq object we're making things from.
#' @param axes A numeric vector of the axes to include.
make_pcoa_df = function(ord, physeq, axes){
    # Calculate the axis weights
    weights = round(ord$values$Relative_eig, 3) * 100

    # Make the data frame
    ord_df = plot_ordination(physeq, ord, axes = axes, justDF = TRUE)
    ord_long = (ord_df
                %>% gather(AxisX, ValueX, starts_with('Axis.'))
                %>% left_join(ord_df)
                %>% gather(AxisY, ValueY, starts_with('Axis.'))
                %>% mutate(AxisX = factor(paste(AxisX,
                                        paste(weights[axis_num(AxisX)], '%',
                                                 sep = ''))),
                           AxisY = factor(paste(AxisY,
                                        paste(weights[axis_num(AxisY)], '%',
                                                 sep = '')))))
    return(ord_long)
}

#### make_ord_df --------------------------------------------------------------

#' Make a data frame of the ordination
#'
#' Take a phyloseq object and generate a data frame of the distance-based
#' ordination of the samples for plotting. This function has been tested with
#' ordination methods 'PCoA' and 'RDA'. I can't make any promises if you use a
#' different ordination method.
#'
#' @param physeq A phyloseq object with an OTU table and sample data. The table
#'   should be rarefied (or relative abundance) so that the distance metrics
#'   will be meaningful.
#' @param dist_meth The distance method to be use. Must be one of the methods
#'   accepted by the \code{phyloseq::distance()} function. Default is 'bray'. If
#'   'jaccard' is used, adds the \code{binary = TRUE} argument.
#' @param ord_meth The ordination method. Must be one of the methods accepted by
#'   the \code{phyloseq::ordinate()} function. Default is 'PCoA'.
#' @param scree_only If \code{TRUE}, this function will print the scree plot of
#'   the requested ordination and then exit. Good for deciding how many axes you
#'   care about. Default is \code{FALSE}.
#' @param axes A vector of integers indicating which ordination axes to include
#'   in the data frame. Defaults to \code{1:4}.
make_ord_df = function(physeq, dist_meth = 'bray', ord_meth = 'PCoA',
                  scree_only = FALSE, axes = 1:4){
    # Get the distance object and do the ordination
    if (dist_meth == 'jaccard'){
        d = distance(physeq, method = dist_meth, binary = TRUE)
    } else {
        d = distance(physeq, method = dist_meth)
    }
    ord = ordinate(physeq, ord_meth, d)

    # Scree
    if (scree_only) {
        print(phyloseq::plot_scree(ord))
        return()
    }

    if (ord_meth == 'PCoA'){
        ord_long = make_pcoa_df(ord, physeq, axes)
    } else if (ord_meth == 'RDA'){
        ord_long = make_rda_df(ord, physeq, axes)
    } else {
        ord_long = tryCatch(make_pcoa_df(ord, physeq, axes))
        if (is.data.frame(ord_long)){
            warn('Data frame produced, but untested with this ordination method. Double check before plotting.')
        } else {
            ord_long = tryCatch(make_rda_df(ord, physeq, axes))
            if (is.data.frame(ord_long)) {
                warn('Data frame produced, but untested with this ordination method. Double check before plotting.')
            } else {
                stop('Data frame could not be produced. Try \'PCoA\' or \'RDA\' ordination methods.')
            }
        }

        return(ord_long)
    }

    return(ord_long)

}

### Plot the ordination --------------------------------------------------------
#### plt_ord ------------------------------------------------------------------
#' Plot the ordination
#'
#' Make a multi-axis PCoA plot from the data frame
#' @param ord_long The ordination data frame produced by \code{make_ord_df}
#' @param colour The name of the column to use to colour the points.
#' @param shape The name of the coloumn governing the shape of the points.
#' @param size The size of the points. Passed to the \code{geom_point()} size
#' argument and defaults to 1.
#' @param pt_alph The transparency of the points. Default is 0.7
plt_ord = function(ord_long, colour = NULL, shape = NULL, size = 1,
                   pt_alph = 0.7){
    ord_plt = ggplot(ord_long, aes(ValueX, ValueY))

    if (!is.null(colour) & !(is.null(shape))) {
        ord_plt = ord_plt +
            geom_point(aes_string(colour = colour, shape = shape),
                       size = size,
                       alpha = pt_alph)
    } else if (!is.null(colour)){
        ord_plt = ord_plt +
            geom_point(aes_string(colour = colour), alpha = pt_alph, size = size)
    } else if (!is.null(shape)){
        ord_plt = ord_plt +
            geom_point(aes_string(shape = shape), alpha = pt_alph, size = size)
    } else {
        ord_plt = ord_plt +
            geom_point(alpha = pt_alph, size = size)
    }

    ord_plt = ord_plt +
        facet_grid(AxisY ~ AxisX)

    return(ord_plt)
}
